/**
 * Kho MẪU XE của seed — thông số kỹ thuật có thật của các dòng xe đang chạy dịch vụ ở Việt Nam.
 *
 * Vì sao khai theo "mẫu xe" chứ không theo "chiếc xe": một gian hàng 40 xe không có 40 dòng xe
 * khác nhau, nó có ~15 dòng nhân lên nhiều chiếc. Tách mẫu ra khỏi chiếc cho phép sinh đội xe
 * lớn mà mọi chiếc vẫn có thông số ĐÚNG với dòng của nó — thay vì bịa 40 bộ số rời rạc.
 *
 * Giá thuê dài hạn và giá có tài xế KHÔNG gõ tay: chúng suy từ giá ngày bằng công thức dưới,
 * nên quan hệ giữa các mức giá luôn hợp lệ (xem `LONG_TERM_SUGGEST_RATIO` ở @xeprime/types).
 * Gõ tay 30 con số là cách chắc chắn để có một chiếc "giá tháng rẻ hơn 3 ngày thuê".
 */
import {
  BODY_TYPE,
  FUEL_TYPE,
  LONG_TERM_PRICE_HINT_DAYS_PER_MONTH,
  TRANSMISSION_TYPE,
  VEHICLE_TYPE,
} from '@xeprime/types';

export interface VehicleModelSpec {
  key: string;
  vehicleType: string;
  /** Khoá trong danh mục `vehicle_brand` (bảng `catalog_items`), KHÔNG phải nhãn hiển thị. */
  brand: string;
  model: string;
  /** Kiểu dáng thân xe — chỉ ô tô; xe máy để null. */
  bodyType: string | null;
  fuelType: string;
  transmission: string | null;
  seatCount: number;
  engineCc: number | null;
  horsepower: number | null;
  /** dài × rộng × cao (mm) + khối lượng bản thân (kg). Null với xe máy (không hiển thị). */
  size: readonly [number, number, number, number] | null;
  /** Mức tiêu thụ L/100km: đô thị / cao tốc / kết hợp. Null với xe điện. */
  consumption: readonly [number, number, number] | null;
  /** Giá thuê ngày thường (VND). Mọi mức giá khác suy từ đây. */
  weekday: number;
  /** Giá cuối tuần. */
  weekend: number;
  /** Giá theo giờ — null = dòng xe này không cho thuê giờ. */
  hourly: number | null;
  /** Dòng xe phù hợp cho thuê dài hạn (sedan/CUV/MPV phổ thông, xe máy). */
  longTerm: boolean;
  /** Dòng xe có phục vụ kèm tài xế (xe từ 5 chỗ trở lên, không phải xe máy/bán tải nhỏ). */
  withDriver: boolean;
  features: readonly string[];
  /** Ảnh Unsplash ghim theo id — phần tử đầu là ảnh đại diện, còn lại là gallery. */
  photos: readonly string[];
  description: string;
}

/**
 * Tỉ lệ quy giá tháng từ giá ngày. Nằm giữa `LONG_TERM_SUGGEST_RATIO` (0.65–0.8) — thuê tháng
 * rẻ hơn thuê lẻ là điều kiện để gói dài hạn có nghĩa, nhưng không rẻ tới mức lỗ.
 *
 * ADR 0011: con số này CHỈ để gợi ý mức giá tháng tham chiếu của một chiếc xe. Nó KHÔNG dùng để
 * suy ngày trả hay giá gói — ngày trả tính bằng tháng lịch (`addCalendarMonthsVn`).
 */
const LONG_TERM_RATIO = 0.7;

/** Chi phí tài xế cộng thêm mỗi ngày (nội thành), và hệ số cho lộ trình liên tỉnh. */
const DRIVER_DAILY_SURCHARGE = 600_000;
const DRIVER_INTER_CITY_RATIO = 1.25;
const DRIVER_ONE_WAY_RATIO = 1.6;

const roundTo = (value: number, step: number): number => Math.round(value / step) * step;

/** Giá tháng tham chiếu của một mẫu xe — null khi mẫu đó không phục vụ thuê dài hạn. */
export function monthlyPriceOf(spec: VehicleModelSpec): number | null {
  if (!spec.longTerm) return null;
  return roundTo(spec.weekday * LONG_TERM_PRICE_HINT_DAYS_PER_MONTH * LONG_TERM_RATIO, 100_000);
}

/** Bộ ba giá có tài xế — null khi mẫu đó không phục vụ kèm tài xế. */
export function driverPricesOf(
  spec: VehicleModelSpec,
): { daily: number; interCity: number; oneWay: number } | null {
  if (!spec.withDriver) return null;
  const daily = roundTo(spec.weekday + DRIVER_DAILY_SURCHARGE, 50_000);
  return {
    daily,
    interCity: roundTo(daily * DRIVER_INTER_CITY_RATIO, 50_000),
    oneWay: roundTo(daily * DRIVER_ONE_WAY_RATIO, 50_000),
  };
}

// Ảnh: 27 photo id Unsplash đã dùng và kiểm chứng ở seed trước — không bịa id mới, vì id sai
// cho ra thẻ xe vỡ ảnh mà không ai để ý cho tới lúc mở marketplace.
const P = {
  sedanA: '1550355291-bbee04a92027',
  sedanB: '1502877338535-766e1452684a',
  sedanC: '1549317661-bd32c8ce0db2',
  sedanD: '1553440569-bcc63803a83d',
  suvA: '1533473359331-0135ef1b58bf',
  suvB: '1568605117036-5fe5e7bab0b7',
  suvC: '1519641471654-76ce0107ad1b',
  cuvA: '1568772585407-9361f9bf3a87',
  cuvB: '1570125909232-eb263c188f7e',
  cuvC: '1617788138017-80ad40651399',
  miniA: '1494976388531-d1058494cdd8',
  miniB: '1503376780353-7e6692767b70',
  mpvA: '1558980664-10ea292d6d12',
  mpvB: '1558981359-219d6364c9c8',
  mpvC: '1558981403-c5f9899a28bc',
  pickupA: '1558981806-ec527fa84c39',
  pickupB: '1504215680853-026ed2a45def',
  vanA: '1536700503339-1e4b06520771',
  vanB: '1542362567-b07e54358753',
  evA: '1571068316344-75bc76f77890',
  evB: '1599819811279-d5ad9cccf838',
  evC: '1609630875171-b1321377ee65',
  bikeA: '1511919884226-fd3cad34687c',
  bikeB: '1549399542-7e3f8b79c341',
  bikeC: '1492144534655-ae79c964c9d7',
  scene: '1469854523086-cc02fe5d8800',
} as const;

/**
 * 30 dòng xe phủ đủ MỌI chiều của bộ lọc marketplace: 9 kiểu dáng, 4 loại nhiên liệu, 5 kiểu
 * hộp số, số chỗ từ 2 tới 16, và cả xe máy. Không dòng nào là hàng hiếm — đây là những xe thật
 * sự đang chạy dịch vụ, nên giá và thông số đối chiếu được với thị trường.
 */
export const VEHICLE_MODELS: readonly VehicleModelSpec[] = [
  // ── Hạng A / mini ────────────────────────────────────────────────────────
  {
    key: 'kia-morning',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'kia',
    model: 'Morning',
    bodyType: BODY_TYPE.MINI,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.AUTOMATIC,
    seatCount: 5,
    engineCc: 1248,
    horsepower: 84,
    size: [3595, 1595, 1485, 935],
    consumption: [6.8, 4.9, 5.6],
    weekday: 550_000,
    weekend: 650_000,
    hourly: 80_000,
    longTerm: true,
    withDriver: false,
    features: ['bluetooth', 'usb', 'airbag', 'reverse_sensor'],
    photos: [P.miniA, P.miniB],
    description:
      'Xe cỡ nhỏ dễ luồn phố, chỗ đậu nào cũng vừa. Phù hợp đi lại trong thành phố và người mới lái.',
  },
  {
    key: 'hyundai-i10',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'hyundai',
    model: 'Grand i10',
    bodyType: BODY_TYPE.MINI,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.AUTOMATIC,
    seatCount: 5,
    engineCc: 1197,
    horsepower: 86,
    size: [3815, 1680, 1520, 950],
    consumption: [6.5, 4.7, 5.4],
    weekday: 520_000,
    weekend: 620_000,
    hourly: 75_000,
    longTerm: true,
    withDriver: false,
    features: ['bluetooth', 'usb', 'airbag', 'backup_camera'],
    photos: [P.miniB, P.miniA],
    description: 'Hạng A tiết kiệm xăng, máy lạnh mát, bảo dưỡng đúng hạn tại hãng.',
  },
  {
    key: 'vinfast-fadil',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'vinfast',
    model: 'Fadil',
    bodyType: BODY_TYPE.MINI,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.CVT,
    seatCount: 5,
    engineCc: 1399,
    horsepower: 98,
    size: [3995, 1735, 1505, 1075],
    consumption: [7.2, 5.1, 5.9],
    weekday: 540_000,
    weekend: 640_000,
    hourly: 80_000,
    longTerm: true,
    withDriver: false,
    features: ['bluetooth', 'usb', 'airbag', 'backup_camera', 'screen'],
    photos: [P.miniA, P.scene],
    description: 'Hạng A gầm hơi cao, chạy phố và đường tỉnh đều êm.',
  },

  // ── Sedan ────────────────────────────────────────────────────────────────
  {
    key: 'toyota-vios',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'toyota',
    model: 'Vios',
    bodyType: BODY_TYPE.SEDAN,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.CVT,
    seatCount: 5,
    engineCc: 1496,
    horsepower: 106,
    size: [4425, 1730, 1475, 1105],
    consumption: [7.4, 5.2, 6.0],
    weekday: 650_000,
    weekend: 800_000,
    hourly: 90_000,
    longTerm: true,
    withDriver: true,
    features: ['bluetooth', 'backup_camera', 'usb', 'map', 'airbag'],
    photos: [P.sedanA, P.sedanB, P.sedanC],
    description:
      'Sedan quốc dân tiết kiệm xăng, phù hợp đi phố lẫn về quê. Xe bảo dưỡng định kỳ tại hãng.',
  },
  {
    key: 'honda-city',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'honda',
    model: 'City',
    bodyType: BODY_TYPE.SEDAN,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.CVT,
    seatCount: 5,
    engineCc: 1498,
    horsepower: 119,
    size: [4580, 1748, 1467, 1153],
    consumption: [7.1, 5.0, 5.8],
    weekday: 680_000,
    weekend: 820_000,
    hourly: 95_000,
    longTerm: true,
    withDriver: true,
    features: ['bluetooth', 'backup_camera', 'usb', 'screen', 'airbag', 'reverse_sensor'],
    photos: [P.sedanB, P.sedanD],
    description: 'Sedan hạng B rộng rãi, cách âm tốt, ghế sau đủ chỗ cho ba người lớn.',
  },
  {
    key: 'hyundai-accent',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'hyundai',
    model: 'Accent',
    bodyType: BODY_TYPE.SEDAN,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.AUTOMATIC,
    seatCount: 5,
    engineCc: 1368,
    horsepower: 100,
    size: [4440, 1729, 1470, 1120],
    consumption: [7.3, 5.1, 5.9],
    weekday: 640_000,
    weekend: 780_000,
    hourly: 90_000,
    longTerm: true,
    withDriver: true,
    features: ['bluetooth', 'backup_camera', 'usb', 'airbag'],
    photos: [P.sedanC, P.sedanA],
    description: 'Sedan hạng B quen thuộc với tài xế dịch vụ, chi phí vận hành thấp.',
  },
  {
    key: 'kia-k3',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'kia',
    model: 'K3',
    bodyType: BODY_TYPE.SEDAN,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.CVT,
    seatCount: 5,
    engineCc: 1598,
    horsepower: 126,
    size: [4640, 1800, 1440, 1275],
    consumption: [7.6, 5.3, 6.2],
    weekday: 720_000,
    weekend: 880_000,
    hourly: 100_000,
    longTerm: true,
    withDriver: true,
    features: ['bluetooth', 'backup_camera', 'usb', 'screen', 'airbag', 'sunroof'],
    photos: [P.sedanD, P.sedanB],
    description: 'Sedan hạng C nhiều trang bị, cửa sổ trời, ghế da — hợp đi công tác.',
  },
  {
    key: 'mazda-3',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'mazda',
    model: 'Mazda3',
    bodyType: BODY_TYPE.SEDAN,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.AUTOMATIC,
    seatCount: 5,
    engineCc: 1496,
    horsepower: 118,
    size: [4660, 1795, 1445, 1320],
    consumption: [7.4, 5.0, 6.0],
    weekday: 780_000,
    weekend: 950_000,
    hourly: 110_000,
    longTerm: true,
    withDriver: true,
    features: ['bluetooth', 'backup_camera', 'usb', 'screen', 'airbag', 'gps'],
    photos: [P.sedanA, P.sedanD],
    description: 'Sedan hạng C nội thất đẹp, vô-lăng nhẹ, cách âm khá — lái đường dài đỡ mệt.',
  },
  {
    key: 'toyota-camry',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'toyota',
    model: 'Camry',
    bodyType: BODY_TYPE.SEDAN,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.AUTOMATIC,
    seatCount: 5,
    engineCc: 1987,
    horsepower: 165,
    size: [4885, 1840, 1445, 1520],
    consumption: [9.2, 6.0, 7.2],
    weekday: 1_350_000,
    weekend: 1_600_000,
    hourly: null,
    longTerm: true,
    withDriver: true,
    features: ['bluetooth', 'backup_camera', 'camera_360', 'usb', 'screen', 'airbag', 'gps', 'etc'],
    photos: [P.sedanD, P.sedanC],
    description: 'Sedan hạng D dùng đón khách, đi sự kiện. Nội thất da, ghế sau chỉnh điện.',
  },
  {
    key: 'mercedes-c200',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'mercedes',
    model: 'C200 Avantgarde',
    bodyType: BODY_TYPE.SEDAN,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.AUTOMATIC,
    seatCount: 5,
    engineCc: 1497,
    horsepower: 204,
    size: [4751, 1820, 1438, 1625],
    consumption: [9.6, 6.2, 7.5],
    weekday: 2_400_000,
    weekend: 2_900_000,
    hourly: null,
    longTerm: false,
    withDriver: true,
    features: [
      'bluetooth',
      'backup_camera',
      'camera_360',
      'usb',
      'screen',
      'airbag',
      'gps',
      'sunroof',
      'etc',
    ],
    photos: [P.sedanC, P.sedanD],
    description: 'Xe sang cho đám cưới, đón đối tác. Giao xe kèm tài xế mặc vest theo yêu cầu.',
  },

  // ── CUV / SUV ────────────────────────────────────────────────────────────
  {
    key: 'kia-seltos',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'kia',
    model: 'Seltos',
    bodyType: BODY_TYPE.CUV,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.CVT,
    seatCount: 5,
    engineCc: 1353,
    horsepower: 138,
    size: [4370, 1800, 1615, 1350],
    consumption: [8.4, 5.8, 6.8],
    weekday: 800_000,
    weekend: 950_000,
    hourly: 110_000,
    longTerm: true,
    withDriver: true,
    features: ['bluetooth', 'backup_camera', 'usb', 'screen', 'airbag', 'sunroof', 'reverse_sensor'],
    photos: [P.cuvA, P.cuvB],
    description: 'Crossover gầm cao, cốp rộng, đi phượt cuối tuần vừa đủ chỗ cho 4 người và hành lý.',
  },
  {
    key: 'hyundai-creta',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'hyundai',
    model: 'Creta',
    bodyType: BODY_TYPE.CUV,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.CVT,
    seatCount: 5,
    engineCc: 1497,
    horsepower: 115,
    size: [4300, 1790, 1635, 1320],
    consumption: [8.2, 5.6, 6.6],
    weekday: 780_000,
    weekend: 930_000,
    hourly: 110_000,
    longTerm: true,
    withDriver: true,
    features: ['bluetooth', 'backup_camera', 'usb', 'screen', 'airbag', 'reverse_sensor'],
    photos: [P.cuvB, P.cuvC],
    description: 'Crossover cỡ B gầm cao, dễ lái, phù hợp gia đình nhỏ đi chơi xa.',
  },
  {
    key: 'mitsubishi-xforce',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'mitsubishi',
    model: 'Xforce',
    bodyType: BODY_TYPE.CUV,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.CVT,
    seatCount: 5,
    engineCc: 1499,
    horsepower: 105,
    size: [4390, 1810, 1660, 1290],
    consumption: [8.0, 5.5, 6.5],
    weekday: 800_000,
    weekend: 960_000,
    hourly: 110_000,
    longTerm: true,
    withDriver: true,
    features: ['bluetooth', 'backup_camera', 'camera_360', 'usb', 'screen', 'airbag'],
    photos: [P.cuvC, P.cuvA],
    description: 'Crossover mới, khoảng sáng gầm cao, camera 360 — chạy đường xấu yên tâm.',
  },
  {
    key: 'toyota-corolla-cross-hev',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'toyota',
    model: 'Corolla Cross HEV',
    bodyType: BODY_TYPE.CUV,
    fuelType: FUEL_TYPE.HYBRID,
    transmission: TRANSMISSION_TYPE.CVT,
    seatCount: 5,
    engineCc: 1798,
    horsepower: 122,
    size: [4460, 1825, 1620, 1420],
    consumption: [4.4, 4.0, 4.2],
    weekday: 950_000,
    weekend: 1_150_000,
    hourly: null,
    longTerm: true,
    withDriver: true,
    features: ['bluetooth', 'backup_camera', 'usb', 'screen', 'airbag', 'gps', 'etc'],
    photos: [P.cuvA, P.cuvC],
    description: 'Bản hybrid cực tiết kiệm — chạy phố khoảng 4,4 L/100km, không cần cắm sạc.',
  },
  {
    key: 'vinfast-vf5',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'vinfast',
    model: 'VF 5 Plus',
    bodyType: BODY_TYPE.CUV,
    fuelType: FUEL_TYPE.ELECTRIC,
    transmission: TRANSMISSION_TYPE.AUTOMATIC,
    seatCount: 5,
    engineCc: null,
    horsepower: 134,
    size: [3965, 1720, 1580, 1250],
    consumption: null,
    weekday: 750_000,
    weekend: 900_000,
    hourly: 100_000,
    longTerm: true,
    withDriver: false,
    features: ['bluetooth', 'backup_camera', 'usb', 'screen', 'airbag'],
    photos: [P.evA, P.evB],
    description: 'Xe điện cỡ nhỏ, không tốn tiền xăng. Giao xe pin đầy, trạm sạc phủ khắp thành phố.',
  },
  {
    key: 'vinfast-vf8',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'vinfast',
    model: 'VF 8 Eco',
    bodyType: BODY_TYPE.SUV,
    fuelType: FUEL_TYPE.ELECTRIC,
    transmission: TRANSMISSION_TYPE.AUTOMATIC,
    seatCount: 5,
    engineCc: null,
    horsepower: 349,
    size: [4750, 1934, 1667, 2200],
    consumption: null,
    weekday: 1_500_000,
    weekend: 1_800_000,
    hourly: null,
    longTerm: true,
    withDriver: true,
    features: ['bluetooth', 'camera_360', 'usb', 'screen', 'airbag', 'gps', 'sunroof'],
    photos: [P.evB, P.evC],
    description: 'SUV điện cỡ D, khoang rộng, tăng tốc nhanh và cực êm — hợp đi đường dài.',
  },
  {
    key: 'toyota-fortuner',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'toyota',
    model: 'Fortuner',
    bodyType: BODY_TYPE.SUV,
    fuelType: FUEL_TYPE.DIESEL,
    transmission: TRANSMISSION_TYPE.AUTOMATIC,
    seatCount: 7,
    engineCc: 2393,
    horsepower: 149,
    size: [4795, 1855, 1835, 2100],
    consumption: [9.5, 7.0, 8.0],
    weekday: 1_400_000,
    weekend: 1_700_000,
    hourly: null,
    longTerm: true,
    withDriver: true,
    features: ['bluetooth', 'backup_camera', 'usb', 'screen', 'airbag', 'spare_tire', 'gps'],
    photos: [P.suvA, P.suvB],
    description: 'SUV 7 chỗ máy dầu, gầm cao, chở cả nhà đi đường đèo hay đường xấu đều chắc.',
  },
  {
    key: 'ford-everest',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'ford',
    model: 'Everest',
    bodyType: BODY_TYPE.SUV,
    fuelType: FUEL_TYPE.DIESEL,
    transmission: TRANSMISSION_TYPE.AUTOMATIC,
    seatCount: 7,
    engineCc: 1996,
    horsepower: 168,
    size: [4914, 1923, 1842, 2250],
    consumption: [9.2, 6.8, 7.8],
    weekday: 1_500_000,
    weekend: 1_800_000,
    hourly: null,
    longTerm: true,
    withDriver: true,
    features: ['bluetooth', 'camera_360', 'usb', 'screen', 'airbag', 'spare_tire', 'gps', 'etc'],
    photos: [P.suvB, P.suvC],
    description: 'SUV 7 chỗ nhiều công nghệ hỗ trợ lái, khoang lái yên tĩnh, kéo được rơ-moóc nhẹ.',
  },
  {
    key: 'hyundai-santafe',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'hyundai',
    model: 'Santa Fe',
    bodyType: BODY_TYPE.SUV,
    fuelType: FUEL_TYPE.DIESEL,
    transmission: TRANSMISSION_TYPE.DCT,
    seatCount: 7,
    engineCc: 2151,
    horsepower: 200,
    size: [4785, 1900, 1710, 1900],
    consumption: [8.6, 6.2, 7.2],
    weekday: 1_450_000,
    weekend: 1_750_000,
    hourly: null,
    longTerm: true,
    withDriver: true,
    features: ['bluetooth', 'camera_360', 'usb', 'screen', 'airbag', 'gps', 'sunroof'],
    photos: [P.suvC, P.suvA],
    description: 'SUV 7 chỗ máy dầu hộp số ly hợp kép, hàng ghế ba gập phẳng cho cốp rất rộng.',
  },

  // ── MPV ──────────────────────────────────────────────────────────────────
  {
    key: 'mitsubishi-xpander',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'mitsubishi',
    model: 'Xpander',
    bodyType: BODY_TYPE.MPV,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.AUTOMATIC,
    seatCount: 7,
    engineCc: 1499,
    horsepower: 105,
    size: [4595, 1750, 1750, 1245],
    consumption: [8.0, 5.6, 6.6],
    weekday: 800_000,
    weekend: 950_000,
    hourly: 110_000,
    longTerm: true,
    withDriver: true,
    features: ['bluetooth', 'backup_camera', 'usb', 'screen', 'airbag', 'child_seat'],
    photos: [P.mpvA, P.mpvB],
    description: 'MPV 7 chỗ bán chạy nhất phân khúc — gầm cao, tiết kiệm xăng, hợp gia đình.',
  },
  {
    key: 'toyota-innova',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'toyota',
    model: 'Innova',
    bodyType: BODY_TYPE.MPV,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.AUTOMATIC,
    seatCount: 8,
    engineCc: 1998,
    horsepower: 134,
    size: [4735, 1830, 1795, 1680],
    consumption: [9.4, 6.6, 7.8],
    weekday: 900_000,
    weekend: 1_100_000,
    hourly: null,
    longTerm: true,
    withDriver: true,
    features: ['bluetooth', 'backup_camera', 'usb', 'airbag', 'spare_tire'],
    photos: [P.mpvB, P.mpvC],
    description: 'MPV 8 chỗ bền bỉ, khoang rộng, lựa chọn quen thuộc cho tour và đưa đón sân bay.',
  },
  {
    key: 'toyota-veloz',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'toyota',
    model: 'Veloz Cross',
    bodyType: BODY_TYPE.MPV,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.CVT,
    seatCount: 7,
    engineCc: 1496,
    horsepower: 105,
    size: [4475, 1750, 1700, 1245],
    consumption: [7.8, 5.4, 6.4],
    weekday: 850_000,
    weekend: 1_000_000,
    hourly: 115_000,
    longTerm: true,
    withDriver: true,
    features: ['bluetooth', 'backup_camera', 'usb', 'screen', 'airbag', 'child_seat'],
    photos: [P.mpvC, P.mpvA],
    description: 'MPV 7 chỗ đời mới, nhiều trang bị an toàn, ghế hàng hai trượt được.',
  },
  {
    key: 'kia-carnival',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'kia',
    model: 'Carnival',
    bodyType: BODY_TYPE.MPV,
    fuelType: FUEL_TYPE.DIESEL,
    transmission: TRANSMISSION_TYPE.AUTOMATIC,
    seatCount: 7,
    engineCc: 2151,
    horsepower: 199,
    size: [5155, 1995, 1775, 2130],
    consumption: [9.0, 6.4, 7.5],
    weekday: 1_800_000,
    weekend: 2_100_000,
    hourly: null,
    longTerm: true,
    withDriver: true,
    features: ['bluetooth', 'camera_360', 'usb', 'screen', 'airbag', 'gps', 'sunroof', 'etc'],
    photos: [P.mpvA, P.mpvC],
    description: 'MPV cao cấp, cửa trượt điện, ghế thương gia — hợp đón đoàn khách và đi công tác.',
  },

  // ── Bán tải / van / minibus ──────────────────────────────────────────────
  {
    key: 'ford-ranger',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'ford',
    model: 'Ranger XLS',
    bodyType: BODY_TYPE.PICKUP,
    fuelType: FUEL_TYPE.DIESEL,
    transmission: TRANSMISSION_TYPE.AUTOMATIC,
    seatCount: 5,
    engineCc: 1996,
    horsepower: 168,
    size: [5370, 1918, 1884, 2100],
    consumption: [8.8, 6.6, 7.5],
    weekday: 1_100_000,
    weekend: 1_300_000,
    hourly: null,
    longTerm: true,
    withDriver: false,
    features: ['bluetooth', 'backup_camera', 'usb', 'screen', 'airbag', 'spare_tire'],
    photos: [P.pickupA, P.pickupB],
    description: 'Bán tải chở được hàng cồng kềnh, thùng sau phủ composite, đi công trình tốt.',
  },
  {
    key: 'mitsubishi-triton',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'mitsubishi',
    model: 'Triton',
    bodyType: BODY_TYPE.PICKUP,
    fuelType: FUEL_TYPE.DIESEL,
    transmission: TRANSMISSION_TYPE.AUTOMATIC,
    seatCount: 5,
    engineCc: 2442,
    horsepower: 178,
    size: [5320, 1865, 1795, 1995],
    consumption: [9.0, 6.8, 7.7],
    weekday: 950_000,
    weekend: 1_150_000,
    hourly: null,
    longTerm: true,
    withDriver: false,
    features: ['bluetooth', 'backup_camera', 'usb', 'airbag', 'spare_tire'],
    photos: [P.pickupB, P.pickupA],
    description: 'Bán tải máy dầu khoẻ, bán kính quay đầu nhỏ nhất phân khúc — chạy phố dễ hơn.',
  },
  {
    key: 'ford-transit',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'ford',
    model: 'Transit',
    bodyType: BODY_TYPE.MINIBUS,
    fuelType: FUEL_TYPE.DIESEL,
    transmission: TRANSMISSION_TYPE.MANUAL,
    seatCount: 16,
    engineCc: 2198,
    horsepower: 128,
    size: [5780, 2000, 2280, 2600],
    consumption: [12.0, 8.5, 10.0],
    weekday: 1_900_000,
    weekend: 2_200_000,
    hourly: null,
    longTerm: false,
    withDriver: true,
    features: ['bluetooth', 'usb', 'airbag', 'spare_tire'],
    photos: [P.vanA, P.vanB],
    description: 'Xe 16 chỗ cho đoàn đông, hành lý nhiều. Thuê kèm tài xế theo quy định.',
  },
  {
    key: 'hyundai-solati',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'hyundai',
    model: 'Solati',
    bodyType: BODY_TYPE.MINIBUS,
    fuelType: FUEL_TYPE.DIESEL,
    transmission: TRANSMISSION_TYPE.MANUAL,
    seatCount: 16,
    engineCc: 2497,
    horsepower: 168,
    size: [6195, 2038, 2665, 2800],
    consumption: [12.5, 8.8, 10.4],
    weekday: 2_000_000,
    weekend: 2_300_000,
    hourly: null,
    longTerm: false,
    withDriver: true,
    features: ['bluetooth', 'usb', 'airbag', 'spare_tire', 'screen'],
    photos: [P.vanB, P.vanA],
    description: 'Xe 16 chỗ trần cao, đứng thẳng người trong khoang — đi tour dài đỡ mỏi.',
  },
  {
    key: 'suzuki-blind-van',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'suzuki',
    model: 'Blind Van',
    bodyType: BODY_TYPE.VAN,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.MANUAL,
    seatCount: 2,
    engineCc: 970,
    horsepower: 71,
    size: [3675, 1475, 1860, 1030],
    consumption: [8.5, 6.5, 7.2],
    weekday: 600_000,
    weekend: 700_000,
    hourly: 85_000,
    longTerm: true,
    withDriver: false,
    features: ['bluetooth', 'usb', 'spare_tire'],
    photos: [P.vanA, P.scene],
    description: 'Xe van 2 chỗ, được vào phố giờ cấm tải — chở hàng nhẹ, chuyển nhà nhỏ.',
  },
  {
    key: 'suzuki-carry-pro',
    vehicleType: VEHICLE_TYPE.CAR,
    brand: 'suzuki',
    model: 'Carry Pro',
    bodyType: BODY_TYPE.CARGO,
    fuelType: FUEL_TYPE.DIESEL,
    transmission: TRANSMISSION_TYPE.MANUAL,
    seatCount: 2,
    engineCc: 1493,
    horsepower: 88,
    size: [4195, 1675, 1910, 1130],
    consumption: [9.5, 7.0, 8.0],
    weekday: 700_000,
    weekend: 820_000,
    hourly: null,
    longTerm: true,
    withDriver: false,
    features: ['spare_tire', 'bluetooth'],
    photos: [P.pickupB, P.vanA],
    description: 'Xe tải nhẹ 810kg thùng bạt — chuyển nhà, chở hàng chợ đầu mối.',
  },

  // ── Xe máy ───────────────────────────────────────────────────────────────
  {
    key: 'honda-vision',
    vehicleType: VEHICLE_TYPE.MOTORBIKE,
    brand: 'honda',
    model: 'Vision',
    bodyType: null,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.AUTOMATIC,
    seatCount: 2,
    engineCc: 110,
    horsepower: 9,
    size: null,
    consumption: [2.2, 1.9, 2.0],
    weekday: 150_000,
    weekend: 180_000,
    hourly: 30_000,
    longTerm: true,
    withDriver: false,
    features: ['spare_tire'],
    photos: [P.bikeA, P.bikeB],
    description: 'Xe tay ga nhỏ gọn, tiết kiệm xăng nhất phân khúc. Giao kèm 2 nón bảo hiểm.',
  },
  {
    key: 'honda-airblade',
    vehicleType: VEHICLE_TYPE.MOTORBIKE,
    brand: 'honda',
    model: 'Air Blade 160',
    bodyType: null,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.AUTOMATIC,
    seatCount: 2,
    engineCc: 157,
    horsepower: 15,
    size: null,
    consumption: [2.6, 2.2, 2.4],
    weekday: 180_000,
    weekend: 220_000,
    hourly: 35_000,
    longTerm: true,
    withDriver: false,
    features: ['spare_tire'],
    photos: [P.bikeB, P.bikeC],
    description: 'Tay ga 160cc bốc, cốp rộng để vừa nón fullface. Phanh ABS bánh trước.',
  },
  {
    key: 'honda-sh',
    vehicleType: VEHICLE_TYPE.MOTORBIKE,
    brand: 'honda',
    model: 'SH 160i',
    bodyType: null,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.AUTOMATIC,
    seatCount: 2,
    engineCc: 156,
    horsepower: 16,
    size: null,
    consumption: [2.8, 2.3, 2.5],
    weekday: 350_000,
    weekend: 420_000,
    hourly: 60_000,
    longTerm: true,
    withDriver: false,
    features: ['spare_tire'],
    photos: [P.bikeC, P.bikeA],
    description: 'Tay ga cao cấp bánh lớn, chạy đường xóc êm. Có khoá smartkey.',
  },
  {
    key: 'yamaha-exciter',
    vehicleType: VEHICLE_TYPE.MOTORBIKE,
    brand: 'yamaha',
    model: 'Exciter 155',
    bodyType: null,
    fuelType: FUEL_TYPE.GASOLINE,
    transmission: TRANSMISSION_TYPE.MANUAL,
    seatCount: 2,
    engineCc: 155,
    horsepower: 17,
    size: null,
    consumption: [2.5, 2.0, 2.2],
    weekday: 220_000,
    weekend: 260_000,
    hourly: 40_000,
    longTerm: true,
    withDriver: false,
    features: ['spare_tire'],
    photos: [P.bikeA, P.bikeC],
    description: 'Xe côn tay 155cc, hợp phượt đường đèo. Yêu cầu người thuê có kinh nghiệm côn tay.',
  },
  {
    key: 'vinfast-klara',
    vehicleType: VEHICLE_TYPE.MOTORBIKE,
    brand: 'vinfast',
    model: 'Klara S',
    bodyType: null,
    fuelType: FUEL_TYPE.ELECTRIC,
    transmission: TRANSMISSION_TYPE.AUTOMATIC,
    seatCount: 2,
    engineCc: null,
    horsepower: 4,
    size: null,
    consumption: null,
    weekday: 200_000,
    weekend: 240_000,
    hourly: 35_000,
    longTerm: true,
    withDriver: false,
    features: ['spare_tire'],
    photos: [P.bikeB, P.evA],
    description: 'Xe máy điện chạy êm, không tốn xăng. Quãng đường khoảng 90 km mỗi lần sạc đầy.',
  },
];

export const VEHICLE_MODEL_BY_KEY: ReadonlyMap<string, VehicleModelSpec> = new Map(
  VEHICLE_MODELS.map((m) => [m.key, m]),
);

/**
 * Đầu số biển theo tỉnh — biển thật của địa phương, để dữ liệu nhìn vào là đúng vùng.
 * Nguồn: Thông tư 24/2023/TT-BCA (ký hiệu tỉnh giữ nguyên sau sáp nhập 2025).
 */
export const PLATE_PREFIX: Readonly<Record<string, { car: readonly string[]; bike: readonly string[] }>> = {
  '01': { car: ['29A', '30A', '30E', '30F'], bike: ['29B1', '29H1'] }, // Hà Nội
  '31': { car: ['15A', '15C'], bike: ['15B1'] }, // Hải Phòng
  '46': { car: ['75A'], bike: ['75B1'] }, // Huế
  '48': { car: ['43A', '43C'], bike: ['43B1'] }, // Đà Nẵng
  '79': { car: ['51H', '50A', '51K', '51G'], bike: ['59X1', '59H1'] }, // Hồ Chí Minh
  '92': { car: ['65A', '65C'], bike: ['65B1'] }, // Cần Thơ
};

/** Màu xe theo thứ tự luân phiên — không random, để chạy lại seed ra đúng dữ liệu cũ. */
export const VEHICLE_COLORS: readonly string[] = [
  'Trắng',
  'Đen',
  'Bạc',
  'Xám',
  'Đỏ',
  'Xanh dương',
  'Nâu',
];
