/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng nhập: đổi ID token lấy session cookie httpOnly */
        post: operations["AuthController_createSession"];
        /** Đăng xuất: xoá session cookie */
        delete: operations["AuthController_logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng ký bằng email + mật khẩu */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng nhập bằng email + mật khẩu */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quên mật khẩu: gửi link đặt lại qua email */
        post: operations["AuthController_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đặt lại mật khẩu từ token trong email */
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thông tin user hiện tại kèm tenant scope và quyền */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rbac/my-permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quyền của user hiện tại theo từng scope
         * @description Frontend dùng để ẩn/hiện menu. KHÔNG phải nguồn bảo vệ — backend guard mới là nguồn.
         */
        get: operations["RbacController_myPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + readiness (có ping PostgreSQL) */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hồ sơ của user hiện tại */
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cập nhật hồ sơ của chính mình */
        patch: operations["UsersController_updateMe"];
        trace?: never;
    };
    "/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng ký gian hàng mới (tạo ở trạng thái nháp) */
        post: operations["TenantsController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gian hàng của user hiện tại (scope lấy từ membership) */
        get: operations["TenantsController_current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/current/shop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hồ sơ gian hàng của tôi + trạng thái duyệt */
        get: operations["TenantsController_myShop"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/current/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cập nhật hồ sơ gian hàng */
        patch: operations["TenantsController_updateProfile"];
        trace?: never;
    };
    "/tenants/current/submit-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gửi hồ sơ gian hàng cho nền tảng duyệt */
        post: operations["TenantsController_submitReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách xe làm hàng của resource timeline */
        get: operations["CalendarController_resources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sự kiện chiếm lịch trong khoảng thời gian */
        get: operations["CalendarController_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/check-conflict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Xem trước trùng lịch (preview, không phải lớp bảo vệ) */
        post: operations["CalendarController_checkConflict"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tìm xe trên Marketplace (phân trang, filter, sort) */
        get: operations["PublicListingsController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách xe của gian hàng (phân trang, filter, sort) */
        get: operations["VehiclesController_list"];
        put?: never;
        /** Thêm xe mới (mặc định trạng thái public = nháp) */
        post: operations["VehiclesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết một xe */
        get: operations["VehiclesController_getOne"];
        put?: never;
        post?: never;
        /** Xoá mềm xe (chặn nếu còn lịch hiện tại/tương lai) */
        delete: operations["VehiclesController_remove"];
        options?: never;
        head?: never;
        /** Sửa thông tin xe */
        patch: operations["VehiclesController_update"];
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách đơn thuê (phân trang, filter, sort) */
        get: operations["BookingsController_list"];
        put?: never;
        /** Tạo đơn thuê (giữ chỗ lịch, chặn trùng bằng constraint DB) */
        post: operations["BookingsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết một đơn thuê */
        get: operations["BookingsController_getOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Sửa đơn (đổi khung giờ sẽ reschedule lịch) */
        patch: operations["BookingsController_update"];
        trace?: never;
    };
    "/bookings/{id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chuyển trạng thái đơn (validate canTransitionBooking) */
        post: operations["BookingsController_transition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hàng đợi phiếu duyệt (phân trang, lọc theo trạng thái/loại) */
        get: operations["PlatformAdminController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/approvals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết phiếu duyệt (hồ sơ snapshot + lịch sử) */
        get: operations["PlatformAdminController_getOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/approvals/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duyệt phiếu (gian hàng → hoạt động) */
        post: operations["PlatformAdminController_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/approvals/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Từ chối phiếu (cần lý do) */
        post: operations["PlatformAdminController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/approvals/{id}/request-revision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Yêu cầu bổ sung (cần lý do) */
        post: operations["PlatformAdminController_requestRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateSessionDto: {
            /**
             * @description ID token từ Firebase Auth (hoặc `mock:<uid>:<email>:<tên>` khi AUTH_MODE=mock). Chỉ gửi đúng một lần lúc đăng nhập — sau đó dùng session cookie.
             * @example mock:demo-owner:owner@xeprime.test:Chủ shop demo
             */
            idToken: string;
        };
        CurrentTenantSummaryDto: {
            id: string;
            name: string;
            slug: string;
            /** @description Xem TenantStatus trong @xeprime/types */
            status: string;
            /** @description Xem TenantRole trong @xeprime/types */
            roleKey: string;
        };
        MeDto: {
            id: string;
            displayName: string;
            email?: Record<string, never> | null;
            avatarUrl?: Record<string, never> | null;
            /** @description Đã xác thực SĐT chưa — gate cho việc đặt xe/mở shop */
            phoneVerified: boolean;
            tenant?: components["schemas"]["CurrentTenantSummaryDto"] | null;
            /** @description Xem PlatformRole trong @xeprime/types */
            platformRole?: Record<string, never> | null;
            permissions: string[];
        };
        RegisterDto: {
            /** @example matkhau123 */
            password: string;
            /** @example Nguyễn Văn A */
            displayName: string;
            /** @example ban@congty.vn */
            email: string;
        };
        LoginDto: {
            /** @example ban@congty.vn */
            email: string;
            password: string;
        };
        ForgotPasswordDto: {
            /** @example ban@congty.vn */
            email: string;
        };
        ResetPasswordDto: {
            /** @example matkhau123 */
            password: string;
            /** @description Token từ link trong email */
            token: string;
        };
        MyPermissionsDto: {
            /** @enum {string|null} */
            tenantRole?: "shop_owner" | "shop_manager" | "shop_staff" | "shop_viewer" | null;
            /** @enum {string|null} */
            platformRole?: "platform_admin" | "platform_staff" | "reviewer" | "support" | "finance_admin" | null;
            permissions: ("tenant.view" | "tenant.update" | "tenant.submit_review" | "members.view" | "members.invite" | "members.update_role" | "members.remove" | "vehicles.view" | "vehicles.create" | "vehicles.update" | "vehicles.delete" | "vehicles.submit_public" | "vehicles.block_schedule" | "booking_requests.view" | "booking_requests.approve" | "bookings.view" | "bookings.create" | "bookings.update" | "bookings.cancel" | "calendar.view" | "finance.view" | "receipts.create" | "receipts.approve" | "platform.dashboard.view" | "platform.tenants.manage" | "platform.approvals.review" | "platform.audit.view" | "platform.staff.manage")[];
        };
        UserProfileDto: {
            id: string;
            displayName: string;
            email?: Record<string, never> | null;
            phone?: Record<string, never> | null;
            avatarUrl?: Record<string, never> | null;
            phoneVerified: boolean;
        };
        UpdateMeDto: {
            displayName?: string;
            avatarUrl?: string;
        };
        RegisterShopDto: {
            /** @example Cho thuê xe Bình Minh */
            name: string;
            /**
             * @default individual
             * @enum {string}
             */
            tenantType: "individual" | "business";
            /** @example 0901234567 */
            phone?: string;
            email?: string;
        };
        TenantProfileDto: {
            displayName?: string | null;
            bio?: string | null;
            logoUrl?: string | null;
            coverUrl?: string | null;
            address?: string | null;
            provinceCode?: string | null;
            provinceName?: string | null;
            taxCode?: string | null;
            businessLicenseNo?: string | null;
            bankName?: string | null;
            bankAccountNo?: string | null;
            bankAccountName?: string | null;
            qrUrl?: string | null;
        };
        LatestApprovalDto: {
            /** @enum {string} */
            status: "pending" | "approved" | "rejected" | "needs_revision" | "cancelled";
            reason?: string | null;
            /** @description ISO-8601 UTC */
            submittedAt: string;
            reviewedAt?: string | null;
        };
        MyShopDto: {
            id: string;
            code: string;
            slug: string;
            name: string;
            /** @enum {string} */
            tenantType: "individual" | "business";
            /** @enum {string} */
            status: "draft" | "pending_review" | "needs_revision" | "active" | "suspended" | "rejected" | "expired";
            phone?: string | null;
            email?: string | null;
            profile: components["schemas"]["TenantProfileDto"];
            latestApproval?: components["schemas"]["LatestApprovalDto"] | null;
        };
        CurrentTenantDto: {
            id: string;
            code: string;
            slug: string;
            name: string;
            /** @enum {string} */
            tenantType: "individual" | "business";
            /** @enum {string} */
            status: "draft" | "pending_review" | "needs_revision" | "active" | "suspended" | "rejected" | "expired";
            phone?: Record<string, never> | null;
            email?: Record<string, never> | null;
            /**
             * @description Decimal trả về dạng string — ADR 0007
             * @example 4.75
             */
            ratingAvg: string;
            ratingCount: number;
            vehicleCount: number;
            memberCount: number;
            /** @enum {string} */
            myRoleKey: "shop_owner" | "shop_manager" | "shop_staff" | "shop_viewer";
        };
        UpdateTenantProfileDto: {
            displayName?: string;
            bio?: string;
            logoUrl?: string;
            coverUrl?: string;
            address?: string;
            provinceCode?: string;
            provinceName?: string;
            taxCode?: string;
            businessLicenseNo?: string;
            bankName?: string;
            bankAccountNo?: string;
            bankAccountName?: string;
            qrUrl?: string;
        };
        CalendarResourceDto: {
            id: string;
            vehicleId: string;
            name: string;
            plateNumber?: Record<string, never> | null;
            /** @enum {string} */
            vehicleType: "car" | "motorbike";
            /** @enum {string} */
            operationStatus: "available" | "renting" | "maintenance" | "inactive";
        };
        CalendarEventDto: {
            id: string;
            /** @description vehicleId — khớp CalendarResourceDto.id */
            resourceId: string;
            /** @enum {string} */
            type: "booking" | "blocked_range" | "maintenance";
            title: string;
            customerName?: Record<string, never> | null;
            /**
             * @description ISO-8601 UTC
             * @example 2026-07-12T02:00:00.000Z
             */
            startAt: string;
            /**
             * @description ISO-8601 UTC
             * @example 2026-07-15T04:00:00.000Z
             */
            endAt: string;
            /** @description BookingStatus khi type=booking */
            status?: Record<string, never> | null;
            sourceId?: Record<string, never> | null;
        };
        CheckConflictDto: {
            /** @description ID xe (ULID) */
            vehicleId: string;
            /**
             * Format: date-time
             * @description Nhận xe, ISO-8601 UTC
             */
            startAt: string;
            /**
             * Format: date-time
             * @description Trả xe, ISO-8601 UTC
             */
            endAt: string;
            /** @description Bỏ qua nguồn này (khi sửa chính đơn đang xét) */
            excludeSourceId?: string;
        };
        ConflictItemDto: {
            id: string;
            sourceType: string;
            sourceId: string;
        };
        CheckConflictResultDto: {
            /** @description Có trùng lịch hay không */
            hasConflict: boolean;
            conflicts: components["schemas"]["ConflictItemDto"][];
        };
        PublicListingDto: {
            id: string;
            name: string;
            /** @enum {string} */
            vehicleType: "car" | "motorbike";
            /** @enum {string} */
            serviceType: "self_drive" | "with_driver" | "both" | "long_term";
            brand?: Record<string, never> | null;
            model?: Record<string, never> | null;
            seatCount?: Record<string, never> | null;
            fuelType?: Record<string, never> | null;
            mainImageUrl?: Record<string, never> | null;
            /** @description Tiền dạng string — ADR 0007 */
            weekdayPrice?: Record<string, never> | null;
            weekendPrice?: Record<string, never> | null;
            /** @description Tên gian hàng */
            shopName: string;
            /** @description Slug gian hàng cho route /shops/[slug] */
            shopSlug: string;
        };
        PublicListingPageMetaDto: {
            page: number;
            limit: number;
            total: number;
            hasNext: boolean;
        };
        PublicListingPageDto: {
            data: components["schemas"]["PublicListingDto"][];
            meta: components["schemas"]["PublicListingPageMetaDto"];
        };
        VehicleListItemDto: {
            id: string;
            code: string;
            name: string;
            plateNumber?: string | null;
            /** @enum {string} */
            vehicleType: "car" | "motorbike";
            /** @enum {string} */
            serviceType: "self_drive" | "with_driver" | "both" | "long_term";
            brand?: string | null;
            model?: string | null;
            manufactureYear?: number | null;
            seatCount?: number | null;
            /** @enum {string} */
            operationStatus: "available" | "renting" | "maintenance" | "inactive";
            /** @enum {string} */
            publicStatus: "draft" | "pending_public_review" | "approved_public" | "needs_revision" | "rejected" | "hidden" | "archived";
            mainImageUrl?: string | null;
            /** @description Tiền dạng string — ADR 0007 */
            weekdayPrice?: string | null;
            weekendPrice?: string | null;
            /** @description ISO-8601 UTC */
            updatedAt: string;
        };
        PaginationMetaDto: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            limit: number;
            /** @example 137 */
            total: number;
            /** @example true */
            hasNext: boolean;
        };
        VehiclePageDto: {
            data: components["schemas"]["VehicleListItemDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        VehicleDetailDto: {
            id: string;
            code: string;
            name: string;
            plateNumber?: string | null;
            /** @enum {string} */
            vehicleType: "car" | "motorbike";
            /** @enum {string} */
            serviceType: "self_drive" | "with_driver" | "both" | "long_term";
            brand?: string | null;
            model?: string | null;
            manufactureYear?: number | null;
            seatCount?: number | null;
            /** @enum {string} */
            operationStatus: "available" | "renting" | "maintenance" | "inactive";
            /** @enum {string} */
            publicStatus: "draft" | "pending_public_review" | "approved_public" | "needs_revision" | "rejected" | "hidden" | "archived";
            mainImageUrl?: string | null;
            /** @description Tiền dạng string — ADR 0007 */
            weekdayPrice?: string | null;
            weekendPrice?: string | null;
            /** @description ISO-8601 UTC */
            updatedAt: string;
            color?: string | null;
            /** @enum {string|null} */
            fuelType?: "gasoline" | "diesel" | "electric" | "hybrid" | null;
            description?: string | null;
            /** @description ISO-8601 UTC */
            createdAt: string;
        };
        CreateVehicleDto: {
            /**
             * @description Mã xe nội bộ, duy nhất trong gian hàng
             * @example XE-001
             */
            code: string;
            /** @example Toyota Vios 2022 */
            name: string;
            /** @enum {string} */
            vehicleType: "car" | "motorbike";
            /**
             * @default self_drive
             * @enum {string}
             */
            serviceType: "self_drive" | "with_driver" | "both" | "long_term";
            /** @example 51K-123.45 */
            plateNumber?: string;
            brand?: string;
            model?: string;
            manufactureYear?: number;
            color?: string;
            seatCount?: number;
            /** @enum {string} */
            fuelType?: "gasoline" | "diesel" | "electric" | "hybrid";
            /**
             * @default available
             * @enum {string}
             */
            operationStatus: "available" | "renting" | "maintenance" | "inactive";
            description?: string;
            /** @description URL ảnh đại diện xe */
            mainImageUrl?: string;
            /**
             * @description Giá ngày thường, string thập phân — ADR 0007
             * @example 600000
             */
            weekdayPrice?: string;
            /**
             * @description Giá cuối tuần
             * @example 750000
             */
            weekendPrice?: string;
        };
        UpdateVehicleDto: {
            /**
             * @description Mã xe nội bộ, duy nhất trong gian hàng
             * @example XE-001
             */
            code?: string;
            /** @example Toyota Vios 2022 */
            name?: string;
            /** @enum {string} */
            vehicleType?: "car" | "motorbike";
            /**
             * @default self_drive
             * @enum {string}
             */
            serviceType: "self_drive" | "with_driver" | "both" | "long_term";
            /** @example 51K-123.45 */
            plateNumber?: string;
            brand?: string;
            model?: string;
            manufactureYear?: number;
            color?: string;
            seatCount?: number;
            /** @enum {string} */
            fuelType?: "gasoline" | "diesel" | "electric" | "hybrid";
            /**
             * @default available
             * @enum {string}
             */
            operationStatus: "available" | "renting" | "maintenance" | "inactive";
            description?: string;
            /** @description URL ảnh đại diện xe */
            mainImageUrl?: string;
            /**
             * @description Giá ngày thường, string thập phân — ADR 0007
             * @example 600000
             */
            weekdayPrice?: string;
            /**
             * @description Giá cuối tuần
             * @example 750000
             */
            weekendPrice?: string;
        };
        BookingListItemDto: {
            id: string;
            code: string;
            vehicleId: string;
            vehicleName: string;
            vehiclePlate?: string | null;
            customerName: string;
            customerPhone?: string | null;
            /** @enum {string} */
            status: "reserved" | "confirmed" | "active" | "completed" | "cancelled" | "no_show";
            /** @enum {string} */
            serviceType: "self_drive" | "with_driver" | "both" | "long_term";
            /** @description ISO-8601 UTC */
            pickupAt: string;
            /** @description ISO-8601 UTC */
            returnAt: string;
            /** @description Tiền dạng string — ADR 0007 */
            totalAmount: string;
            paidAmount: string;
            depositAmount: string;
            /** @description ISO-8601 UTC */
            createdAt: string;
        };
        BookingPageDto: {
            data: components["schemas"]["BookingListItemDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        BookingDetailDto: {
            id: string;
            code: string;
            vehicleId: string;
            vehicleName: string;
            vehiclePlate?: string | null;
            customerName: string;
            customerPhone?: string | null;
            /** @enum {string} */
            status: "reserved" | "confirmed" | "active" | "completed" | "cancelled" | "no_show";
            /** @enum {string} */
            serviceType: "self_drive" | "with_driver" | "both" | "long_term";
            /** @description ISO-8601 UTC */
            pickupAt: string;
            /** @description ISO-8601 UTC */
            returnAt: string;
            /** @description Tiền dạng string — ADR 0007 */
            totalAmount: string;
            paidAmount: string;
            depositAmount: string;
            /** @description ISO-8601 UTC */
            createdAt: string;
            baseAmount: string;
            deliveryFee: string;
            discountAmount: string;
            actualPickupAt?: string | null;
            actualReturnAt?: string | null;
            note?: string | null;
            /** @description ISO-8601 UTC */
            updatedAt: string;
        };
        CreateBookingDto: {
            /** @description ID xe (ULID) */
            vehicleId: string;
            /** @example Nguyễn Văn A */
            customerName: string;
            /** @example 0901234567 */
            customerPhone?: string;
            /**
             * @default self_drive
             * @enum {string}
             */
            serviceType: "self_drive" | "with_driver" | "both" | "long_term";
            /** @description Nhận xe (ISO-8601) */
            pickupAt: string;
            /** @description Trả xe (ISO-8601), phải sau nhận xe */
            returnAt: string;
            /**
             * @description Tiền thuê gốc, string thập phân — ADR 0007
             * @example 600000
             */
            baseAmount?: string;
            /** @example 0 */
            deliveryFee?: string;
            /** @example 0 */
            discountAmount?: string;
            /** @example 0 */
            depositAmount?: string;
            note?: string;
        };
        UpdateBookingDto: {
            /** @example Nguyễn Văn A */
            customerName?: string;
            /** @example 0901234567 */
            customerPhone?: string;
            /** @enum {string} */
            serviceType?: "self_drive" | "with_driver" | "both" | "long_term";
            /** @description Nhận xe (ISO-8601) */
            pickupAt?: string;
            /** @description Trả xe (ISO-8601) */
            returnAt?: string;
            /** @example 600000 */
            baseAmount?: string;
            /** @example 0 */
            deliveryFee?: string;
            /** @example 0 */
            discountAmount?: string;
            /** @example 0 */
            depositAmount?: string;
            /** @example 0 */
            paidAmount?: string;
            note?: string;
        };
        TransitionBookingDto: {
            /**
             * @description Trạng thái đích
             * @enum {string}
             */
            status: "reserved" | "confirmed" | "active" | "completed" | "cancelled" | "no_show";
            /** @description Thời điểm nhận xe thực tế (khi → active) */
            actualPickupAt?: string;
            /** @description Thời điểm trả xe thực tế (khi → completed) */
            actualReturnAt?: string;
        };
        ApprovalTaskListItemDto: {
            id: string;
            tenantId?: string | null;
            tenantName?: string | null;
            /** @enum {string} */
            targetType: "tenant" | "vehicle" | "tenant_document" | "vehicle_document";
            targetId: string;
            /** @enum {string} */
            status: "pending" | "approved" | "rejected" | "needs_revision" | "cancelled";
            submittedBy: string;
            submittedByName?: string | null;
            /** @description ISO-8601 UTC */
            submittedAt: string;
            reviewedAt?: string | null;
            reason?: string | null;
        };
        ApprovalTaskPageDto: {
            data: components["schemas"]["ApprovalTaskListItemDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        ApprovalTenantSummaryDto: {
            id: string;
            code: string;
            name: string;
            tenantType: string;
            status: string;
            phone?: string | null;
            email?: string | null;
        };
        ApprovalLogEntryDto: {
            /** @enum {string} */
            action: "submit" | "approve" | "reject" | "request_revision" | "cancel" | "resubmit";
            fromStatus?: string | null;
            toStatus: string;
            note?: string | null;
            actorName?: string | null;
            /** @description ISO-8601 UTC */
            createdAt: string;
        };
        ApprovalTaskDetailDto: {
            id: string;
            tenantId?: string | null;
            tenantName?: string | null;
            /** @enum {string} */
            targetType: "tenant" | "vehicle" | "tenant_document" | "vehicle_document";
            targetId: string;
            /** @enum {string} */
            status: "pending" | "approved" | "rejected" | "needs_revision" | "cancelled";
            submittedBy: string;
            submittedByName?: string | null;
            /** @description ISO-8601 UTC */
            submittedAt: string;
            reviewedAt?: string | null;
            reason?: string | null;
            /** @description Snapshot hồ sơ lúc gửi duyệt */
            snapshot?: {
                [key: string]: unknown;
            } | null;
            tenant?: components["schemas"]["ApprovalTenantSummaryDto"] | null;
            logs: components["schemas"]["ApprovalLogEntryDto"][];
        };
        ReviewActionDto: {
            /** @description Lý do / ghi chú gửi cho chủ shop */
            reason?: string;
        };
        ApiErrorBodyDto: {
            /** @example BOOKING_SCHEDULE_CONFLICT */
            code: string;
            /** @example Xe đã có đơn khác trong khoảng thời gian này */
            message: string;
            /** @description Chi tiết bổ sung, ví dụ danh sách lỗi validate */
            details?: Record<string, never>;
        };
        ApiErrorDto: {
            error: components["schemas"]["ApiErrorBodyDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    AuthController_forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    RbacController_myPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyPermissionsDto"];
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileDto"];
                };
            };
        };
    };
    UsersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileDto"];
                };
            };
        };
    };
    TenantsController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterShopDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyShopDto"];
                };
            };
        };
    };
    TenantsController_current: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentTenantDto"];
                };
            };
        };
    };
    TenantsController_myShop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyShopDto"];
                };
            };
        };
    };
    TenantsController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTenantProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyShopDto"];
                };
            };
        };
    };
    TenantsController_submitReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyShopDto"];
                };
            };
        };
    };
    CalendarController_resources: {
        parameters: {
            query: {
                /** @description Đầu khoảng, ISO-8601 UTC */
                startAt: string;
                /** @description Cuối khoảng, ISO-8601 UTC */
                endAt: string;
                vehicleType?: "car" | "motorbike";
                /** @description Tìm theo tên xe hoặc biển số */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarResourceDto"][];
                };
            };
        };
    };
    CalendarController_events: {
        parameters: {
            query: {
                /** @description Đầu khoảng, ISO-8601 UTC */
                startAt: string;
                /** @description Cuối khoảng, ISO-8601 UTC */
                endAt: string;
                vehicleType?: "car" | "motorbike";
                /** @description Tìm theo tên xe hoặc biển số */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEventDto"][];
                };
            };
        };
    };
    CalendarController_checkConflict: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckConflictDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckConflictResultDto"];
                };
            };
        };
    };
    PublicListingsController_search: {
        parameters: {
            query?: {
                /** @description car | motorbike */
                vehicleType?: "car" | "motorbike";
                serviceType?: "self_drive" | "with_driver" | "both" | "long_term";
                /** @description Hãng xe */
                brand?: string;
                /** @description Số chỗ tối thiểu */
                minSeats?: number;
                /** @description Tìm theo tên/hãng/model */
                q?: string;
                sort?: "newest" | "price_asc" | "price_desc";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicListingPageDto"];
                };
            };
        };
    };
    VehiclesController_list: {
        parameters: {
            query?: {
                /** @description Tìm theo tên/mã/biển số/hãng/model */
                q?: string;
                vehicleType?: "car" | "motorbike";
                serviceType?: "self_drive" | "with_driver" | "both" | "long_term";
                operationStatus?: "available" | "renting" | "maintenance" | "inactive";
                publicStatus?: "draft" | "pending_public_review" | "approved_public" | "needs_revision" | "rejected" | "hidden" | "archived";
                sort?: "newest" | "name_asc" | "code_asc" | "price_asc" | "price_desc";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehiclePageDto"];
                };
            };
        };
    };
    VehiclesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVehicleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleDetailDto"];
                };
            };
        };
    };
    VehiclesController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleDetailDto"];
                };
            };
        };
    };
    VehiclesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                    };
                };
            };
        };
    };
    VehiclesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVehicleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleDetailDto"];
                };
            };
        };
    };
    BookingsController_list: {
        parameters: {
            query?: {
                /** @description Tìm theo tên khách/SĐT/mã đơn */
                q?: string;
                status?: "reserved" | "confirmed" | "active" | "completed" | "cancelled" | "no_show";
                /** @description Lọc theo xe */
                vehicleId?: string;
                /** @description Trả xe từ (ISO) — lọc cho panel quá hạn/sắp trả */
                returnFrom?: string;
                /** @description Trả xe đến (ISO) */
                returnTo?: string;
                sort?: "newest" | "pickup_asc" | "pickup_desc" | "return_asc";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingPageDto"];
                };
            };
        };
    };
    BookingsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetailDto"];
                };
            };
        };
    };
    BookingsController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetailDto"];
                };
            };
        };
    };
    BookingsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBookingDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetailDto"];
                };
            };
        };
    };
    BookingsController_transition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionBookingDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetailDto"];
                };
            };
        };
    };
    PlatformAdminController_list: {
        parameters: {
            query?: {
                status?: "pending" | "approved" | "rejected" | "needs_revision" | "cancelled";
                targetType?: "tenant" | "vehicle" | "tenant_document" | "vehicle_document";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalTaskPageDto"];
                };
            };
        };
    };
    PlatformAdminController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalTaskDetailDto"];
                };
            };
        };
    };
    PlatformAdminController_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewActionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalTaskDetailDto"];
                };
            };
        };
    };
    PlatformAdminController_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewActionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalTaskDetailDto"];
                };
            };
        };
    };
    PlatformAdminController_requestRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewActionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalTaskDetailDto"];
                };
            };
        };
    };
}
