/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng nhập: đổi ID token lấy session cookie httpOnly */
        post: operations["AuthController_createSession"];
        /** Đăng xuất: xoá session cookie */
        delete: operations["AuthController_logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng ký bằng email + mật khẩu */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng nhập bằng email + mật khẩu */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quên mật khẩu: gửi link đặt lại qua email */
        post: operations["AuthController_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đặt lại mật khẩu từ token trong email */
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thông tin user hiện tại kèm tenant scope và quyền */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rbac/my-permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quyền của user hiện tại theo từng scope
         * @description Frontend dùng để ẩn/hiện menu. KHÔNG phải nguồn bảo vệ — backend guard mới là nguồn.
         */
        get: operations["RbacController_myPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + readiness (có ping PostgreSQL) */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hồ sơ của user hiện tại */
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cập nhật hồ sơ của chính mình */
        patch: operations["UsersController_updateMe"];
        trace?: never;
    };
    "/tenants/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gian hàng của user hiện tại (scope lấy từ membership) */
        get: operations["TenantsController_current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách xe làm hàng của resource timeline */
        get: operations["CalendarController_resources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sự kiện chiếm lịch trong khoảng thời gian */
        get: operations["CalendarController_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tìm xe trên Marketplace (phân trang, filter, sort) */
        get: operations["PublicListingsController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateSessionDto: {
            /**
             * @description ID token từ Firebase Auth (hoặc `mock:<uid>:<email>:<tên>` khi AUTH_MODE=mock). Chỉ gửi đúng một lần lúc đăng nhập — sau đó dùng session cookie.
             * @example mock:demo-owner:owner@xeprime.test:Chủ shop demo
             */
            idToken: string;
        };
        CurrentTenantSummaryDto: {
            id: string;
            name: string;
            slug: string;
            /** @description Xem TenantStatus trong @xeprime/types */
            status: string;
            /** @description Xem TenantRole trong @xeprime/types */
            roleKey: string;
        };
        MeDto: {
            id: string;
            displayName: string;
            email?: Record<string, never> | null;
            avatarUrl?: Record<string, never> | null;
            /** @description Đã xác thực SĐT chưa — gate cho việc đặt xe/mở shop */
            phoneVerified: boolean;
            tenant?: components["schemas"]["CurrentTenantSummaryDto"] | null;
            /** @description Xem PlatformRole trong @xeprime/types */
            platformRole?: Record<string, never> | null;
            permissions: string[];
        };
        RegisterDto: {
            /** @example matkhau123 */
            password: string;
            /** @example Nguyễn Văn A */
            displayName: string;
            /** @example ban@congty.vn */
            email: string;
        };
        LoginDto: {
            /** @example ban@congty.vn */
            email: string;
            password: string;
        };
        ForgotPasswordDto: {
            /** @example ban@congty.vn */
            email: string;
        };
        ResetPasswordDto: {
            /** @example matkhau123 */
            password: string;
            /** @description Token từ link trong email */
            token: string;
        };
        MyPermissionsDto: {
            /** @enum {string|null} */
            tenantRole?: "shop_owner" | "shop_manager" | "shop_staff" | "shop_viewer" | null;
            /** @enum {string|null} */
            platformRole?: "platform_admin" | "platform_staff" | "reviewer" | "support" | "finance_admin" | null;
            permissions: ("tenant.view" | "tenant.update" | "tenant.submit_review" | "members.view" | "members.invite" | "members.update_role" | "members.remove" | "vehicles.view" | "vehicles.create" | "vehicles.update" | "vehicles.delete" | "vehicles.submit_public" | "vehicles.block_schedule" | "booking_requests.view" | "booking_requests.approve" | "bookings.view" | "bookings.create" | "bookings.update" | "bookings.cancel" | "calendar.view" | "finance.view" | "receipts.create" | "receipts.approve" | "platform.dashboard.view" | "platform.tenants.manage" | "platform.approvals.review" | "platform.audit.view" | "platform.staff.manage")[];
        };
        UserProfileDto: {
            id: string;
            displayName: string;
            email?: Record<string, never> | null;
            phone?: Record<string, never> | null;
            avatarUrl?: Record<string, never> | null;
            phoneVerified: boolean;
        };
        UpdateMeDto: {
            displayName?: string;
            avatarUrl?: string;
        };
        CurrentTenantDto: {
            id: string;
            code: string;
            slug: string;
            name: string;
            /** @enum {string} */
            tenantType: "individual" | "business";
            /** @enum {string} */
            status: "draft" | "pending_review" | "needs_revision" | "active" | "suspended" | "rejected" | "expired";
            phone?: Record<string, never> | null;
            email?: Record<string, never> | null;
            /**
             * @description Decimal trả về dạng string — ADR 0007
             * @example 4.75
             */
            ratingAvg: string;
            ratingCount: number;
            vehicleCount: number;
            memberCount: number;
            /** @enum {string} */
            myRoleKey: "shop_owner" | "shop_manager" | "shop_staff" | "shop_viewer";
        };
        CalendarResourceDto: {
            id: string;
            vehicleId: string;
            name: string;
            plateNumber?: Record<string, never> | null;
            /** @enum {string} */
            vehicleType: "car" | "motorbike";
            /** @enum {string} */
            operationStatus: "available" | "renting" | "maintenance" | "inactive";
        };
        CalendarEventDto: {
            id: string;
            /** @description vehicleId — khớp CalendarResourceDto.id */
            resourceId: string;
            /** @enum {string} */
            type: "booking" | "blocked_range" | "maintenance";
            title: string;
            customerName?: Record<string, never> | null;
            /**
             * @description ISO-8601 UTC
             * @example 2026-07-12T02:00:00.000Z
             */
            startAt: string;
            /**
             * @description ISO-8601 UTC
             * @example 2026-07-15T04:00:00.000Z
             */
            endAt: string;
            /** @description BookingStatus khi type=booking */
            status?: Record<string, never> | null;
            sourceId?: Record<string, never> | null;
        };
        PublicListingDto: {
            id: string;
            name: string;
            /** @enum {string} */
            vehicleType: "car" | "motorbike";
            /** @enum {string} */
            serviceType: "self_drive" | "with_driver" | "both" | "long_term";
            brand?: Record<string, never> | null;
            model?: Record<string, never> | null;
            seatCount?: Record<string, never> | null;
            fuelType?: Record<string, never> | null;
            mainImageUrl?: Record<string, never> | null;
            /** @description Tiền dạng string — ADR 0007 */
            weekdayPrice?: Record<string, never> | null;
            weekendPrice?: Record<string, never> | null;
            /** @description Tên gian hàng */
            shopName: string;
            /** @description Slug gian hàng cho route /shops/[slug] */
            shopSlug: string;
        };
        PublicListingPageMetaDto: {
            page: number;
            limit: number;
            total: number;
            hasNext: boolean;
        };
        PublicListingPageDto: {
            data: components["schemas"]["PublicListingDto"][];
            meta: components["schemas"]["PublicListingPageMetaDto"];
        };
        ApiErrorBodyDto: {
            /** @example BOOKING_SCHEDULE_CONFLICT */
            code: string;
            /** @example Xe đã có đơn khác trong khoảng thời gian này */
            message: string;
            /** @description Chi tiết bổ sung, ví dụ danh sách lỗi validate */
            details?: Record<string, never>;
        };
        ApiErrorDto: {
            error: components["schemas"]["ApiErrorBodyDto"];
        };
        PaginationMetaDto: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            limit: number;
            /** @example 137 */
            total: number;
            /** @example true */
            hasNext: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    AuthController_forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    RbacController_myPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyPermissionsDto"];
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileDto"];
                };
            };
        };
    };
    UsersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileDto"];
                };
            };
        };
    };
    TenantsController_current: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentTenantDto"];
                };
            };
        };
    };
    CalendarController_resources: {
        parameters: {
            query: {
                /** @description Đầu khoảng, ISO-8601 UTC */
                startAt: string;
                /** @description Cuối khoảng, ISO-8601 UTC */
                endAt: string;
                vehicleType?: "car" | "motorbike";
                /** @description Tìm theo tên xe hoặc biển số */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarResourceDto"][];
                };
            };
        };
    };
    CalendarController_events: {
        parameters: {
            query: {
                /** @description Đầu khoảng, ISO-8601 UTC */
                startAt: string;
                /** @description Cuối khoảng, ISO-8601 UTC */
                endAt: string;
                vehicleType?: "car" | "motorbike";
                /** @description Tìm theo tên xe hoặc biển số */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEventDto"][];
                };
            };
        };
    };
    PublicListingsController_search: {
        parameters: {
            query?: {
                /** @description car | motorbike */
                vehicleType?: "car" | "motorbike";
                serviceType?: "self_drive" | "with_driver" | "both" | "long_term";
                /** @description Hãng xe */
                brand?: string;
                /** @description Số chỗ tối thiểu */
                minSeats?: number;
                /** @description Tìm theo tên/hãng/model */
                q?: string;
                sort?: "newest" | "price_asc" | "price_desc";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicListingPageDto"];
                };
            };
        };
    };
}
