import { BOOKING_REQUEST_STATUS, BOOKING_REQUEST_STATUS_META } from '@xeprime/types';

/** Các trạng thái shop hay lọc ở inbox (chờ duyệt để mặc định, rồi các trạng thái đã xử lý). */
export const BOOKING_REQUEST_STATUS_OPTIONS = [
  {
    value: BOOKING_REQUEST_STATUS.PENDING_HOST_APPROVAL,
    label: BOOKING_REQUEST_STATUS_META[BOOKING_REQUEST_STATUS.PENDING_HOST_APPROVAL].label,
  },
  {
    value: BOOKING_REQUEST_STATUS.CONVERTED_TO_BOOKING,
    label: BOOKING_REQUEST_STATUS_META[BOOKING_REQUEST_STATUS.CONVERTED_TO_BOOKING].label,
  },
  {
    value: BOOKING_REQUEST_STATUS.REJECTED_BY_HOST,
    label: BOOKING_REQUEST_STATUS_META[BOOKING_REQUEST_STATUS.REJECTED_BY_HOST].label,
  },
  {
    value: BOOKING_REQUEST_STATUS.CANCELLED_BY_CUSTOMER,
    label: BOOKING_REQUEST_STATUS_META[BOOKING_REQUEST_STATUS.CANCELLED_BY_CUSTOMER].label,
  },
];
